### ISSUE TITLE
Using BinaryFormatter is obsolete

### ISSUE THREAD

**Issue by securigy** [Azure-Samples/azure-search-dotnet-scale#6]
Please take a look at this:
https://learn.microsoft.com/en-us/dotnet/core/compatibility/serialization/5.0/binaryformatter-serialization-obsolete

According to it, use of bf.Serialize(ms, json);
should be eliminated in EstimateObjSize function.

**Comment by HeidiSteen** [comment]
Thanks for filing the issue, the sample is now updated.
